name: Casualties of the State
favicon: null
layout_spectrum: 0.4196092034690082
typography_spectrum: 0.4964570284355432
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.013418886112049222
  lightness: 0.9635296755004674
  saturation: 0.20140128955245018
  rhythmicContrast: 0.5207239172887057
purpose: []
