name: Casualties of the State
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4964570284355432
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0c11'
    - '#c1c3cf'
    - '#22252c'
    - '#7f8690'
    - '#4b4c51'
  brandStrength: 0.6875
  lightness: 0.8125
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
